media:
  input: static/media
  output: /media

settings:
  content:
    merge: true
  commit:
    identity: user

content:
  - name: homepage
    label: Website content
    type: file
    path: content/_index.md
    operations:
      delete: false
    fields:
      - name: body
        label: Page
        type: rich-text
