baseURL = "https://example.org/"
languageCode = "en"
title = "European Coaching Program"
disableKinds = ["taxonomy", "term"]

[params]
  description = "A two-year training and certification program for barbershop coaches in Europe."

[markup.goldmark.renderer]
  unsafe = true
